# Generated by Django 3.2.13 on 2022-06-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainActions',
            fields=[
                ('domain', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('first_time_seen', models.TextField(blank=True, null=True)),
                ('last_time_seen', models.TextField(blank=True, null=True)),
                ('permitted', models.BooleanField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domain_actions',
                'managed': False,
            },
        ),
    ]
